let citas = [
  { autor: 'Albert Einstein', texto: 'No poseo talentos especiales. Solo soy apasionadamente curioso.' },
  { autor: 'Alan Kay', texto: 'La mejor forma de predecir el futuro es inventarlo.' },
  { autor: 'Amelia Earhart', texto: 'Lo más difícil es tomar la decisión de actuar. El resto es simplemente tenacidad.' },
  { autor: 'Aristotle', texto: 'La calidad no es un acto, es un hábito.' },
  { autor: 'Benjamin Franklin', texto: 'Dímelo y lo olvidaré. Enséñamelo y lo recordaré. Involúcrame y lo aprenderé.' },
  { autor: 'Charles R. Swindoll', texto: 'La vida es 10% lo que te ocurre y 90% cómo reaccionas.' },
  { autor: 'Jane Goodall', texto: 'Lo que haces hace una diferencia. Y debes decidir qué tipo de diferencia quieres hacer.' },
  { autor: 'John Muir', texto: 'El poder de la imaginación nos hace infinitos.' },
  { autor: 'Mark Twain', texto: 'Los dos días más importantes de tu vida son el día que naciste y el día que descubres por qué.' },
  { autor: 'Anónimo', texto: 'Semanas de programación te pueden ahorrar horas de planeación.' },
  { autor: 'Grace Hopper', texto: 'La frase más peligrosa en cualquier idioma es: "Siempre lo hemos hecho así."' },
  { autor: 'Steve Jobs', texto: 'La innovación distingue a un líder de un seguidor.' },
  { autor: 'Linus Torvalds', texto: 'Inteligencia es la habilidad de evitar hacer trabajo, logrando más con menos esfuerzo.' },
  { autor: 'Ada Lovelace', texto: 'Imagina una máquina que pueda componer música, pintar cuadros o resolver ecuaciones.' },
  { autor: 'Margaret Hamilton', texto: 'El software era tan nuevo que nadie sabía cómo llamarlo.' },
  { autor: 'Alan Turing', texto: 'La inteligencia de una máquina puede juzgarse por su habilidad para sorprender.' },
  { autor: 'Barbara Liskov', texto: 'El diseño de software no es arte, es trabajo técnico con impacto humano.' },
  { autor: 'Dennis Ritchie', texto: 'El arte de programar es pensar antes de escribir.' },
  { autor: 'Robert C. Martin', texto: 'Limpieza de código es respeto por los que vendrán después de ti.' },
  { autor: 'Yoda', texto: 'Hazlo o no lo hagas. No existe el intento.' },
  { autor: 'Carl Sagan', texto: 'En algún lugar, algo increíble espera ser descubierto.' },
  { autor: 'Marie Curie', texto: 'Nada en la vida debe ser temido, solo comprendido.' },
  { autor: 'Richard Feynman', texto: 'No entiendes realmente algo hasta que puedas explicarlo a tu abuela.' },
  { autor: 'Seymour Papert', texto: 'El mejor aprendizaje ocurre cuando el estudiante ama lo que está haciendo.' },
  { autor: 'Nikola Tesla', texto: 'El presente es suyo, pero el futuro por el que realmente trabajé es mío.' },
  { autor: 'Isaac Newton', texto: 'Si he visto más lejos, es porque estoy parado sobre los hombros de gigantes.' },
  { autor: 'Blaise Pascal', texto: 'El corazón tiene razones que la razón no entiende.' },
  { autor: 'Rosa Parks', texto: 'Nunca debes tener miedo de lo que haces cuando sabes que estás en lo correcto.' },
  { autor: 'Neil deGrasse Tyson', texto: 'Cuando estudias el universo, te das cuenta que eres parte de él.' },
  { autor: 'David Bohm', texto: 'El pensamiento crea el mundo y luego dice: “Yo no lo hice.”' },
  { autor: 'Thomas Edison', texto: 'No he fallado. He encontrado 10,000 formas que no funcionan.' },
  // ...(Aquí continuarían hasta completar las 150 citas. Las puedo seguir en más bloques si lo deseas).
];
